.origin 0
.entrypoint START

#define PRU0_R31_VEC_VALID (1<<5)
#define SIGNUM 3

#define DELAY_SECONDS 5
#define CLOCK 200000000
#define CLOCKS_PER_LOOP 2
#define DELAYCOUNT DELAY_SECONDS * CLOCK / CLOCKS_PER_LOOP

START:
	MOV	r1, DELAYCOUNT

DELAY:
	SUB	r1, r1, 1
	QBNE	DELAY, r1, 0

	MOV	R31.b0, PRU0_R31_VEC_VALID | SIGNUM
	HALT